### ISSUE TITLE
License

### ISSUE THREAD

**Issue by alaz** [optimaize/webcrawler-verifier#3]
Hi,

Sorry for using issues to ask you a question.

Are you using GNU license intentionally? It would be great if the project's license was more permissive. Please see [more info](http://choosealicense.com/) on the matter.

Best,
Alexander

**Comment by fabiankessler** [comment]
That was a mistake. It probably should have been LGPL instead of GPL. But I can as well change it to MIT. Simple and very permissive.

**Comment by alaz** [comment]
OK, good to know. Looking forward to seeing it released :)
Thanks!

**Comment by fabiankessler** [comment]
I assure you that you can use the current release "0.1" with the MIT license. You can point to this task. 
Since there are no changes right now, I won't release a 0.2 at this time. Looking forward to contributions ;-)
